name: Go Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          go-version: '1.17.5'
      - run: go version
      - run: go test -v ./...
