on: [push]

name: Coverage

jobs:

  check:
    name: Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v.1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
