name: Code coverage

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

     - name: Run coverage
       run: go test -race -covermode=atomic -coverprofile=coverage.out ./... 
     - name: Upload coverage to Codecov
       uses: codecov/codecoc-action@v1.0.3
       with:
         token: $${secrets.CODECOV_TOKEN}}
